### ISSUE TITLE
ionic gesture on canvas

### ISSUE THREAD

**Issue by xcarlo31** [mhartington/ama#12]
do you have a demo for ionic that can be put inside the canvas? for example i choose a picture from gallery and the picture will go into that canvas and then i can resize it using the gestures?

thanks a lot!

**Comment by mhartington** [comment]
Sadly i do not have a demo.

**Comment by xcarlo31** [comment]
i see.. but it is possible right? we tried to use fabric-angular on ionic, it was successful on the ios platform but not on the android platform.
