### ISSUE TITLE
Is there any support for AndroidWear in the works?

### ISSUE THREAD

**Issue by nishantroy** [mhartington/ama#14]
Just got myself a Moto 360 and I was wondering if I can whip up an Ionic app for it instead of having to go native?

**Comment by mhartington** [comment]
So this would fall in the realm of a cordova plugin. 

Now there an android-wear plugin, though I have not personally tested it.
https://github.com/tgardner/cordova-androidwear

There's also a sample project provided

https://github.com/tgardner/cordova-androidwear-example

I personally don't have a smart watch (not cool enough) so I have no way of personally testing it out.
