### ISSUE TITLE
What's your favorite programming language? + 2 questions

### ISSUE THREAD

**Issue by ihadeed** [mhartington/ama#2]
1. What is your favorite programming language?
2. How long ago did you start programming?
3. What is your major part at Driftyco?

**Comment by ibby93** [comment]
Also I wanted to say hello :) ... I see you name all over the place when I search anything about Ionic!

**Comment by mhartington** [comment]
Hi there! 

1) Obviously JavaScript, but I like lua and any kind of shell script as well. 
2) I started programing probably around 20 (25 right now). Was a bit of a hobby between my college class (Graphic Design Major)
3) My major role is dev advocate, but that covers a lot. Basically any questions that a dev could have during they're development, I'm there to answer. Also work on docs, create examples/tutorial, and speak at conferences & meetups
