### ISSUE TITLE
Did you always have an interest in software development?

### ISSUE THREAD

**Issue by philliphartin** [mhartington/ama#28]
Did you always have an interest in software, or did you find your skill set led you there?

**Comment by mhartington** [comment]
Nope, I originally thought I was going to go into carpentry/wood working for a living. 
I had some interest in Game Design, but never the software side of things.

In college I took some CS courses to meet my requirements, but never really thought any more of it. 
Then senior year of Graphic Design (my major) we did some web development and thats when I got interested. Over the next few years I just dove into it and learned as much as I could.
