### ISSUE TITLE
How useful is vim/neovim in production software

### ISSUE THREAD

**Issue by chidindu-ogbonna** [mhartington/ama#30]
I learnt how to use vim and used it for developing software  (small projects). I have this notion that vim will not go a long way in developing large products, the way other text editors like VScode or atom would. I want to know what you think about this. And if you have any advice for me on using vim for producing large software.

**Comment by mhartington** [comment]
Well let me ask, what do editors like VSCode or Atom offer that N/Vim is missing?

I would say that Vim by it self is limited, but with the right mix of plugins, you can get pretty far. For example, as I write in typescript everyday, my nvim-typescript plugin is my main tool, and I try to get it to provide all the "nice" features that vscode/webstorm have. In doing so, I can stay in neovim and work with large projects without issues.

If navigating a huge codebase is a concern, check out ctrlp, command-t, or denite. I personally use Denite for everything as it's quite extensible and can be used for more than just file searching.
