### ISSUE TITLE
Proper .gitignore for Ionic

### ISSUE THREAD

**Issue by peterpan666** [mhartington/ama#4]
Hi!

First of all, thanks for all the work at Ionic!

What rules are you using for your .gitignore in Ionic? Mine looks like this but not sure if I forgot stuff...

``` gitignore
node_modules/
platforms/
plugins/

resources/*/*
```

**Comment by mhartington** [comment]
It really depends on what you need

Ignoring node_modules, paltform, and plugins are a good start. You could even ignore the internal `www/lib/` and just reinstall every time you clone the repo.

I wouldn't ignore the resources, as those could be useful for others on your team.

**Comment by peterpan666** [comment]
Thanks for the answer!

I thought about `www/lib/` the problem is that other team members will update it by reinstalling it since ionic-cli doesn't care about the current version installed, it just update it to the latest, am I right?

And for the resources, this rule exclude only the generated files for iOS or other platforms, so I was thinking that the team could just regenerate them when needed...

I'm not really sure about all of this, tell me if I'm wrong, I try to learn ;)

Thanks again!
