### ISSUE TITLE
When would you recommend switching up to ionic 2?

### ISSUE THREAD

**Issue by juanferreras** [mhartington/ama#6]
Hey Mike,
I know you probably get this question asked a lot, but I wasn't able to find any answer _after_ Angular 2 beta got released back in December. Would you recommend switching up as soon as ionic 2 beta is released? But until then, is there any particular way ionic 1 apps could be built so they are easier to upgrade if necessary? Lastly, is there any (incredibly) rough date you're planning for the beta release, say, 3 months, 6 months, a year, etc?

Thanks!
Have a nice day.

**Comment by mhartington** [comment]
It really depends on you and your app. If you have a large app that is stable and used by a lot of people, I'd hold off for a while, just until both ionic and angular become stable. 
But you can start to be proactive about it start adopting some best practices  ( controllerAs, writing in ES6/TS) you can make the  transition much easier.
