### ISSUE TITLE
Code pen at http://codepen.io/mhartington/pen/CImqy

### ISSUE THREAD

**Issue by harjotsmart** [mhartington/ama#8]
Hi Mike
I saw your code pen http://codepen.io/mhartington/pen/CImqy
it is awesome
I am trying to hook callback event
but it is not working
can you do a favour if you can update your pen or guide how to hook callback
It will be really helpfull. I also ping you twitter and it's my first time I am using twitter just for you.

Thank you so much for the efforts.

**Comment by mhartington** [comment]
This is rather out of date and not applicable to current released of ionic. You might want to use the default `select` element and use angular's directives for watching change events. I'm not updating that codepen.
